      - name: Build request URL
        id: build
        run: |
          TOKEN="${{ secrets.MW_ACTIONS_BEARER_TOKEN }}"
          if [ -z "$TOKEN" ]; then
            echo "Missing GitHub secret MW_ACTIONS_BEARER_TOKEN" >&2
            exit 1
          fi

          BASE="${{ github.event.inputs.base_url || env.BASE_URL }}"
          SYMS="${{ github.event.inputs.symbols || 'AAPL,TSLA,NVDA,MSFT,SPY,QQQ' }}"
          HOURS="${{ github.event.inputs.hours || '72' }}"

          URL="$BASE/api/cron/sentiment_batch?token=$TOKEN&symbols=$SYMS&hours=$HOURS"
          echo "url=$URL" >> "$GITHUB_OUTPUT"
